// src/components/projects/projects.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'app-projects',
  templateUrl: './projects.component.html',
  styleUrls: ['./projects.component.css']
})
export class ProjectsComponent {}

<!-- PROJECTS -->
<div
  [@fadeInUpAnimationProjects]
  [class.visible]="isVisible"
  class="projects-container"
  id="projects"
>
  <div class="header">
    <h2 class="projects-header">Main Projects</h2>
    <hr class="hr-projects" />
  </div>
  <div class="card">
    <video width="320" height="290" class="card-img-top" controls>
      <source
        src="../../assets/projects-imgs/TheKnifeVideo.mp4"
        type="video/mp4"
      />
      Your browser does not support the video tag.
    </video>
    <div class="card-body">
      <h5 class="card-title">TheKnife</h5>
      <p class="card-text">
        TheKnife aims to rival TheFork by offering users the ability to make
        restaurant reservations and allowing restaurant managers to register and
        manage their restaurants.
      </p>
      <button
        type="button"
        class="btn btn-outline-dark"
        style="font-size: 14px"
      >
        Angular
      </button>
      |
      <button
        type="button"
        class="btn btn-outline-dark"
        style="font-size: 14px"
      >
        JS
      </button>
      |
      <button
        type="button"
        class="btn btn-outline-dark"
        style="font-size: 14px"
      >
        Jest
      </button>
      |
      <button
        type="button"
        class="btn btn-outline-dark"
        style="font-size: 14px"
      >
        Knex
      </button>
      |
      <button
        type="button"
        class="btn btn-outline-dark"
        style="font-size: 14px"
      >
        Docker
      </button>
      |
      <button
        type="button"
        class="btn btn-outline-dark"
        style="font-size: 14px"
      >
        PostgreSQL</button
      ><br /><br />
      <a
        href="https://github.com/ruib07/TheKnife"
        class="btn btn-light"
        target="_blank"
      >
        <img src="../assets/icons/github.svg" /> View Source
      </a>
    </div>
  </div>
  <br />
  <div class="card">
    <img
      src="../../assets/projects-imgs/WeatherApp.webp"
      class="card-img-top"
    />
    <div class="card-body">
      <h5 class="card-title">WeatherApp</h5>
      <p class="card-text">
        Explore global weather conditions effortlessly. Get real-time updates on
        temperature, climate, and hourly forecasts for any city worldwide. Stay
        informed and prepared with our intuitive weather platform.
      </p>
      <button
        type="button"
        class="btn btn-outline-dark"
        style="font-size: 14px"
      >
        HTML
      </button>
      |
      <button
        type="button"
        class="btn btn-outline-dark"
        style="font-size: 14px"
      >
        CSS
      </button>
      |
      <button
        type="button"
        class="btn btn-outline-dark"
        style="font-size: 14px"
      >
        JavaScript
      </button>
      |
      <button
        type="button"
        class="btn btn-outline-dark"
        style="font-size: 14px"
      >
        Public API
      </button>
      <br /><br />
      <a
        href="https://github.com/ruib07/WeatherApp"
        class="btn btn-light"
        target="_blank"
      >
        <img src="../assets/icons/github.svg" /> View Source
      </a>
    </div>
  </div>
  <br />
  <div class="card">
    <img src="../../assets/projects-imgs/event.jpg" class="card-img-top" />
    <div class="card-body">
      <h5 class="card-title">ProEventos</h5>
      <p class="card-text">
        This website is an event website where the user can make a reservation
        to an event, cancel is reservation, update his reservation, make a
        login, register and update the personal data. The website is responsive
        and have a user-friendly design with the minimalistic colors and fonts.
      </p>
      <button
        type="button"
        class="btn btn-outline-dark"
        style="font-size: 14px"
      >
        Angular
      </button>
      |
      <button
        type="button"
        class="btn btn-outline-dark"
        style="font-size: 14px"
      >
        C#
      </button>
      |
      <button
        type="button"
        class="btn btn-outline-dark"
        style="font-size: 14px"
      >
        .NET Web API
      </button>
      |
      <button
        type="button"
        class="btn btn-outline-dark"
        style="font-size: 14px"
      >
        EF Core
      </button>
      |
      <button
        type="button"
        class="btn btn-outline-dark"
        style="font-size: 14px"
      >
        SQL Server</button
      ><br /><br />
      <a
        href="https://github.com/ruib07/ProEventos"
        class="btn btn-light"
        target="_blank"
      >
        <img src="../assets/icons/github.svg" /> View Source
      </a>
    </div>
  </div>
  <br />

  <div class="card">
    <img
      src="../../assets/projects-imgs/burguer-store.webp"
      class="card-img-top"
    />
    <div class="card-body">
      <h5 class="card-title">LanchesMac</h5>
      <p class="card-text">
        This website is an burguer store where the user can buy burguers. The
        website contains and home page with filters, categories, and a carrousel
        slide, a product page with all the burguers, a shop cart, checkout,
        login, register, admin area and the website is responsive.
      </p>
      <button
        type="button"
        class="btn btn-outline-dark"
        style="font-size: 14px"
      >
        C#
      </button>
      |
      <button
        type="button"
        class="btn btn-outline-dark"
        style="font-size: 14px"
      >
        MVC
      </button>
      |
      <button
        type="button"
        class="btn btn-outline-dark"
        style="font-size: 14px"
      >
        HTML
      </button>
      |
      <button
        type="button"
        class="btn btn-outline-dark"
        style="font-size: 14px"
      >
        Bootstrap
      </button>
      |
      <button
        type="button"
        class="btn btn-outline-dark"
        style="font-size: 14px"
      >
        EF Core
      </button>
      |
      <button
        type="button"
        class="btn btn-outline-dark"
        style="font-size: 14px"
      >
        SQL Server</button
      ><br /><br />
      <a
        href="https://github.com/ruib07/LanchesMac"
        class="btn btn-light"
        target="_blank"
      >
        <img src="../assets/icons/github.svg" /> View Source
      </a>
    </div>
  </div>
  <br />

  <div class="card">
    <img src="../../assets/projects-imgs/Tasks-img.webp" class="card-img-top" />
    <div class="card-body">
      <h5 class="card-title">TaskShare App</h5>
      <p class="card-text">
        This mobile app is a task organizer to the user make a list of tasks for
        the day. You can make a login, register, add a task, update a task and
        delete a task.<br />
        The app is minimalistic and have a clean design.
      </p>
      <button
        type="button"
        class="btn btn-outline-dark"
        style="font-size: 14px"
      >
        React Native
      </button>
      |
      <button
        type="button"
        class="btn btn-outline-dark"
        style="font-size: 14px"
      >
        C#
      </button>
      |
      <button
        type="button"
        class="btn btn-outline-dark"
        style="font-size: 14px"
      >
        .NET Web API
      </button>
      |
      <button
        type="button"
        class="btn btn-outline-dark"
        style="font-size: 14px"
      >
        EF Core
      </button>
      |
      <button
        type="button"
        class="btn btn-outline-dark"
        style="font-size: 14px"
      >
        SQL Server</button
      ><br /><br />
      <a
        href="https://github.com/ruib07/TaskShareFrontend"
        class="btn btn-light"
        target="_blank"
      >
        <img src="../assets/icons/github.svg" /> View Frontend Source
      </a>
      |
      <a
        href="https://github.com/ruib07/TaskShareBackend"
        class="btn btn-light"
        target="_blank"
      >
        <img src="../assets/icons/github.svg" /> View Backend Source
      </a>
    </div>
  </div>
</div>
<br /><br /><br />
<!-- END OF PROJECTS -->

// src/components/Projects.tsx
import React from 'react';
import '../styles/Projects.css';
import TheKnifeVideo from '../assets/ProjectsImgs/TheKnifeVideo.mp4';
import WeatherAppImg from '../assets/ProjectsImgs/WeatherApp.webp';
import ProEventosImg from '../assets/ProjectsImgs/event.jpg';
import LanchesMacImg from '../assets/ProjectsImgs/burguer-store.webp';
import TaskShareAppImg from '../assets/ProjectsImgs/Tasks-img.webp';

interface Project {
  title: string;
  description: string;
  techStack: string[];
  videoSrc?: string;
  imageSrc?: string; 
  sourceLinks: { label: string; url: string }[];
}

const projects: Project[] = [
  {
    title: 'TheKnife',
    description:
      'TheKnife aims to rival TheFork by offering users the ability to make restaurant reservations and allowing restaurant managers to register and manage their restaurants.',
    techStack: ['Angular', 'JS', 'Jest', 'Knex', 'Docker', 'PostgreSQL'],
    videoSrc: TheKnifeVideo,
    sourceLinks: [{ label: 'View Source', url: 'https://github.com/ruib07/TheKnife' }],
  },
  {
    title: 'WeatherApp',
    description:
      'Explore global weather conditions effortlessly. Get real-time updates on temperature, climate, and hourly forecasts for any city worldwide.',
    techStack: ['HTML', 'CSS', 'JavaScript', 'Public API'],
    imageSrc: WeatherAppImg,
    sourceLinks: [{ label: 'View Source', url: 'https://github.com/ruib07/WeatherApp' }],
  },
  {
    title: 'ProEventos',
    description:
      'This website is an event website where the user can make a reservation to an event, cancel is reservation, update his reservation, make a login, register and update the personal data.',
    techStack: ['Angular', 'C#', '.NET Web API', 'EF Core', 'SQL Server'],
    imageSrc: ProEventosImg,
    sourceLinks: [{ label: 'View Source', url: 'https://github.com/ruib07/ProEventos' }],
  },
  {
    title: 'LanchesMac',
    description:
      'This website is an burguer store where the user can buy burguers. The website contains filters, categories, a carrousel slide, product page, shop cart, checkout, login, register, admin area.',
    techStack: ['C#', 'MVC', 'HTML', 'Bootstrap', 'EF Core', 'SQL Server'],
    imageSrc: LanchesMacImg,
    sourceLinks: [{ label: 'View Source', url: 'https://github.com/ruib07/LanchesMac' }],
  },
  {
    title: 'TaskShare App',
    description:
      'This mobile app is a task organizer to the user make a list of tasks for the day. You can make a login, register, add a task, update a task and delete a task. The app is minimalistic and have a clean design.',
    techStack: ['React Native', 'C#', '.NET Web API', 'EF Core', 'SQL Server'],
    imageSrc: TaskShareAppImg,
    sourceLinks: [
      { label: 'View Frontend Source', url: 'https://github.com/ruib07/TaskShareFrontend' },
      { label: 'View Backend Source', url: 'https://github.com/ruib07/TaskShareBackend' },
    ],
  },
];

const Projects: React.FC = () => {
  return (
    <div className="projects-container" id="projects">
      <div className="header">
        <h2 className="projects-header">Main Projects</h2>
        <hr className="hr-projects" />
      </div>

      {projects.map((project, index) => (
        <div className="project-card" key={index}>
          <div className="project-content">
            <div className="project-details">
              <h3 className="project-subtitle">Featured Project</h3>
              <h2 className="project-title">{project.title}</h2>
              <p className="project-description">{project.description}</p>
              <div className="tech-stack">
                {project.techStack.map((tech, idx) => (
                  <button className="tech-btn" key={idx}>
                    {tech}
                  </button>
                ))}
              </div>
              {project.sourceLinks.map((link, idx) => (
                <a key={idx} href={link.url} target="_blank" rel="noopener noreferrer" style={{ marginRight: '10px' }} className="source-link">
                  {link.label}
                </a>
              ))}
            </div>

            <div className="project-image">
              {project.videoSrc ? (
                <video className="project-video" controls>
                  <source src={project.videoSrc} type="video/mp4" />
                  Your browser does not support the video tag.
                </video>
              ) : (
                project.imageSrc && <img src={project.imageSrc} alt={`${project.title} Project`} />
              )}
            </div>
          </div>
        </div>
      ))}
    </div>
  );
};

export default Projects;
